# analysis_options.yaml
analyzer:
  errors:
    unused_import: warning
    dead_code: warning
    missing_return: error
    unnecessary_this: warning

linter:
  rules:
    - prefer_single_quotes
    - always_declare_return_types
    - avoid_print
    - prefer_const_constructors
    - public_member_api_docs
    - lines_longer_than_80_chars: false
    - type_annotate_public_apis
    - avoid_renaming_method_parameters
    - prefer_final_fields
    - unnecessary_getters_setters
    - prefer_is_empty
    - avoid_types_on_closure_parameters
    - prefer_adjacent_string_concatenation
    - unnecessary_new
    - prefer_typing_uninitialized_variables
    - use_key_in_widget_constructors