name: streakly_app
description: A Flutter application for tracking challenges and statistics.
publish_to: 'none' 

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/  # Add your image assets here if needed
    - assets/icons/    # Add your icon assets here if needed